# fileName = "sicOpCode.json"
# fileName = "sicXEOpCode.json"
fileName = "opCodeFormat.json"

# SIC OpCOode
# sicOpcode = {
#     'ADD' : '18',
#     'AND' : '40',
#     'COMP' : '28',
#     'DIV' : '24',
#     'J' : '3C',
#     'JEQ' : '30',
#     'JGT' : '34',
#     'JLT' : '38',
#     'JSUB' : '48',
#     'LDA' : '00',
#     'LDCH' : '50',
#     'LDL' : '08',
#     'LDX' : '04',
#     'MUL' : '20',
#     'OR' : '44',
#     'RD' : 'D8',
#     'RSUB' : '4C',
#     'STA' : '0C',
#     'STCH' : '54',
#     'STL' : '14',
#     'STSW' : 'E8',
#     'STX' : '10',
#     'SUB' : '1C',
#     'TD' : 'E0',
#     'TIX' : '2C',
#     'WD' : 'DC'
# }

# SIC/XE OpCode
# sicXEOpcode = {
#     'ADDF' : '58',
#     'ADDR' : '90',
#     'CLEAR' : 'B4',
#     'COMPF' : '88',
#     'COMPR' : 'A0',
#     'DIVF' : '64',
#     'DIVR' : '9C',
#     'FIX' : 'C4',
#     'FLOAT' : 'C0',
#     'HIO' : 'F4',
#     'LDB' : '68',
#     'LDF' : '70',
#     'LDS' : '6C',
#     'LDT' : '74',
#     'LPS' : 'D0',
#     'MULF' : '60',
#     'MULR' : '98',
#     'NORM' : 'C8',
#     'RMO' : 'AC',
#     'SHIFTL' : 'A4',
#     'SHIFTR' : 'A8',
#     'SIO' : 'F0',
#     'SSK' : 'EC',
#     'STB' : '78',
#     'STF' : '80',
#     'STI' : 'D4',
#     'STS' : '7C',
#     'STT' : '84',
#     'SUBF' : '5C',
#     'SUBR' : '94',
#     'SVC' : 'B0',
#     'TIO' : 'F8',
#     'TIXR' : 'B8'
# }

opCodeFormat = {
    'ADD' : 3,
    'AND' : 3,
    'COMP' : 3,
    'DIV' : 3,
    'J' : 3,
    'JEQ' : 3,
    'JGT' : 3,
    'JLT' : 3,
    'JSUB' : 3,
    'LDA' : 3,
    'LDCH' : 3,
    'LDL' : 3,
    'LDX' : 3,
    'MUL' : 3,
    'OR' : 3,
    'RD' : 3,
    'RSUB' : 3,
    'STA' : 3,
    'STCH' : 3,
    'STL' : 3,
    'STSW' : 3,
    'STX' : 3,
    'SUB' : 3,
    'TD' : 3,
    'TIX' : 3,
    'WD' : 3,
    'ADDF' : 3,
    'ADDR' : 2,
    'CLEAR' : 2,
    'COMPF' : 3,
    'COMPR' : 2,
    'DIVF' : 3,
    'DIVR' : 2,
    'FIX' : 1,
    'FLOAT' : 1,
    'HIO' : 1,
    'LDB' : 3,
    'LDF' : 3,
    'LDS' : 3,
    'LDT' : 3,
    'LPS' : 3,
    'MULF' : 3,
    'MULR' : 2,
    'NORM' : 1,
    'RMO' : 2,
    'SHIFTL' : 2,
    'SHIFTR' : 2,
    'SIO' : 1,
    'SSK' : 3,
    'STB' : 3,
    'STF' : 3,
    'STI' : 3,
    'STS' : 3,
    'STT' : 3,
    'SUBF' : 3,
    'SUBR' : 2,
    'SVC' : 2,
    'TIO' : 1,
    'TIXR' : 2
}

import json

with open(file=fileName, mode="w") as file:
    # data = json.dumps(sicOpcode)
    data = json.dumps(opCodeFormat)
    file.write(data)
